#[derive(serde::Serialize, serde::Deserialize, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Indicator {
	pub valid: bool,
	#[serde(rename = "type")]
	pub type_field: String,
	pub speed: f64,
	pub pedals1: f64,
	pub pedals2: f64,
	pub pedals3: f64,
	pub pedals4: f64,
	pub pedals5: f64,
	pub pedals6: f64,
	#[serde(rename = "stick_elevator")]
	pub stick_elevator: f64,
	#[serde(rename = "stick_ailerons")]
	pub stick_ailerons: f64,
	pub vario: f64,
	#[serde(rename = "altitude_hour")]
	pub altitude_hour: f64,
	#[serde(rename = "altitude_min")]
	pub altitude_min: f64,
	#[serde(rename = "altitude_10k")]
	pub altitude_10k: f64,
	#[serde(rename = "altitude1_hour")]
	pub altitude1_hour: f64,
	#[serde(rename = "radio_altitude")]
	pub radio_altitude: f64,
	#[serde(rename = "aviahorizon_roll")]
	pub aviahorizon_roll: f64,
	#[serde(rename = "aviahorizon_pitch")]
	pub aviahorizon_pitch: f64,
	pub bank: f64,
	pub bank1: f64,
	pub turn: f64,
	pub compass: f64,
	pub compass1: f64,
	pub compass2: f64,
	#[serde(rename = "clock_hour")]
	pub clock_hour: f64,
	#[serde(rename = "clock_min")]
	pub clock_min: f64,
	#[serde(rename = "clock_sec")]
	pub clock_sec: f64,
	#[serde(rename = "rpm_min")]
	pub rpm_min: f64,
	#[serde(rename = "rpm1_min")]
	pub rpm1_min: f64,
	#[serde(rename = "rpm_hour")]
	pub rpm_hour: f64,
	#[serde(rename = "rpm1_hour")]
	pub rpm1_hour: f64,
	#[serde(rename = "oil_pressure")]
	pub oil_pressure: f64,
	#[serde(rename = "oil_pressure1")]
	pub oil_pressure1: f64,
	#[serde(rename = "water_temperature_hour")]
	pub water_temperature_hour: f64,
	#[serde(rename = "water_temperature1_hour")]
	pub water_temperature1_hour: f64,
	#[serde(rename = "water_temperature_min")]
	pub water_temperature_min: f64,
	#[serde(rename = "water_temperature1_min")]
	pub water_temperature1_min: f64,
	pub fuel: f64,
	#[serde(rename = "fuel_pressure")]
	pub fuel_pressure: f64,
	#[serde(rename = "fuel_pressure1")]
	pub fuel_pressure1: f64,
	#[serde(rename = "fuel_consume")]
	pub fuel_consume: f64,
	#[serde(rename = "fuel_consume1")]
	pub fuel_consume1: f64,
	pub gears: f64,
	pub gears1: f64,
	pub flaps: f64,
	pub trimmer: f64,
	pub throttle: f64,
	pub throttle1: f64,
	pub weapon2: f64,
	pub weapon3: f64,
	#[serde(rename = "flaps_indicator")]
	pub flaps_indicator: f64,
	#[serde(rename = "gear_l_indicator")]
	pub gear_l_indicator: f64,
	#[serde(rename = "gear_r_indicator")]
	pub gear_r_indicator: f64,
	#[serde(rename = "gear_c_indicator")]
	pub gear_c_indicator: f64,
	#[serde(rename = "trimmer_indicator")]
	pub trimmer_indicator: f64,
	pub mach: f64,
	#[serde(rename = "g_meter")]
	pub g_meter: f64,
	#[serde(rename = "g_meter_min")]
	pub g_meter_min: f64,
	#[serde(rename = "g_meter_max")]
	pub g_meter_max: f64,
	pub aoa: f64,
	pub blister1: f64,
	pub blister2: f64,
	pub blister3: f64,
	pub blister4: f64,
	pub blister5: f64,
	pub blister6: f64,
	pub blister7: f64,
	pub blister8: f64,
	pub blister9: f64,
	pub blister10: f64,
	pub blister11: f64,
	pub blister12: f64,
	pub blister13: f64,
	pub blister14: f64,
	pub blister15: f64,
}
